name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Ajuste conforme o nome da sua branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Etapa 1: Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3  # Atualizado para a versão mais recente

    # Etapa 2: Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Esta ação já está na versão correta

    # Etapa 3: Fazer login no DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2  # Esta ação também já está correta
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Etapa 4: Construir a imagem Docker
    - name: Build Docker image
      run: |
        docker build -t felipegalway/pokedex:latest .

    # Etapa 5: Subir a imagem para o DockerHub
    - name: Push Docker image
      run: |
        docker push felipegalway/pokedex:latest

    # Etapa 6: Conectar no servidor remoto e rodar o container
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.6  # Se houver uma versão mais nova, substitua
      with:
        host: 201.23.3.86
        username: aluno
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 8089
        script: |
          # Parar e remover o container existente
          docker stop pokedex || true
          docker rm pokedex || true
          # Rodar o novo container com a imagem mais recente
          docker run -d --name pokedex -p 8089:8089 felipegalway/pokedex:latest
